package it.polimi.dei.swknights.carcassonne.server.Controller;

import it.polimi.dei.swknights.carcassonne.server.Model.Segnalino;

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Class that implements the abstract idea of a human construction
 * is used as the base of the algorithm use to calculate victory points generated by 
 * controlling constructions
 * 
 */

abstract class Costruzione
{
	/**
	 * Default constructor
	 * Simply initialize a new construction whit at least one element
	 */
	
	public Costruzione()
	{
		this.listaSegnalini = new ArrayList<Segnalino>();
		this.dimensione = 1;
	}
	
	/**
	 * Method used to join two constructions
	 * @param The construction to be join with
	 */

	public void joinCostruzioni(Costruzione costruzione)
	{
		this.dimensione += costruzione.dimensione - this.contaPezziComuni(costruzione);
		this.listaSegnalini.addAll(costruzione.listaSegnalini);
	}
	
	/**
	 * Method used to add a ... to this construction
	 * @param segnalino to be added to this construction
	 */

	public void addSegnalino(Segnalino segnalino)
	{
		this.listaSegnalini.add(segnalino);
	}
	
	/**
	 * Method used to retrive the players that owns this construction
	 * @return the list of the colors of the player controlling this construction
	 */

	public List<Color> controllataDa()
	{
		final int nuovo = 1; // TODO di troppo?
		Map<Color, Integer> contatore = this.inizializzaContatore();
		for (Segnalino segnalino : this.listaSegnalini)
		{
			Color colore = segnalino.getColore();
			int contato = contatore.get(colore) + nuovo;
			contatore.put(colore, contato);
		}
		return this.getListaControllori(contatore);
	}
	
	/**
	 * Method that calculates the victory points generated from structure.
	 * @param colore the color of the considered player
	 * @return the point generated from this construction by the player
	 */

	public abstract int contaPuntiGiocatore(Color colore); //TODO ripensare!

	protected abstract int contaPezziComuni(Costruzione costruzione);

	private Map<Color, Integer> inizializzaContatore()
	{
		// TODO copia incolla è il male!
		Color colori[] = new Color[] { Color.RED, Color.BLUE, Color.GREEN, Color.YELLOW, Color.BLACK };
		final int vuoto = 0; // TODO di troppo?
		Map<Color, Integer> contatore = new HashMap<Color, Integer>();
		for (Color colore : colori)
			contatore.put(colore, vuoto);
		return contatore;
	}

	// TODO da valutare
	private List<Color> getListaControllori(Map<Color, Integer> contatore)
	{
		int max = 1;
		List<Color> controllori = new ArrayList<Color>();
		for (Color colore : contatore.keySet())
		{
			int numeroSegnalini = contatore.get(colore);
			if (numeroSegnalini > max) max = numeroSegnalini;
		}
		for (Color colore : contatore.keySet())
		{
			if (contatore.get(colore) == max) controllori.add(colore);
		}
		return controllori;
	}

	protected int				dimensione;

	private List<Segnalino>	listaSegnalini;
}
